### ISSUE TITLE
NameError: uninitialized constant Magick::MaxRGB

### ISSUE THREAD

**Issue by mjrk** [jakesgordon/sprite-factory#38]
Sprite factory uses a deprecated RMagick constant:

    /home/micha/.rvm/gems/ruby-2.1.3/gems/sprite-factory-1.6.1/lib/sprite_factory/library/rmagick.rb:23:in `create'

Replacing it by 

    target.opacity = Magick::QuantumRange

fixes the issue.

**Comment by jakesgordon** [comment]
This was added in v1.6.2.
Thankyou!
